import grpc
import json
import os
from typing import Any
# These would be generated by grpcio-tools
# from proto import waf_pb2, waf_pb2_grpc

class WafNotifier:
    def __init__(self):
        self.target = os.getenv("CORE_ENGINE_GRPC_TARGET", "localhost:50051")
        # In a real implementation, we would initialize the gRPC stub here
        # self.channel = grpc.insecure_channel(self.target)
        # self.stub = waf_pb2_grpc.WafControlStub(self.channel)

    async def notify_rule_change(self, rule_ids: list[int]):
        """Notifies the core engine to reload specific rules."""
        print(f"DEBUG: Notifying core engine to reload rules: {rule_ids}")
        # request = waf_pb2.ReloadRequest(rule_ids=rule_ids)
        # try:
        #     self.stub.ReloadRules(request)
        # except Exception as e:
        #     print(f"ERROR: Failed to notify core engine: {e}")

    async def notify_config_change(self, key: str, value: Any):
        """Notifies the core engine of a configuration change."""
        print(f"DEBUG: Notifying core engine of config change: {key}={value}")
        # request = waf_pb2.ConfigRequest(key=key, value_json=json.dumps(value))
        # try:
        #     self.stub.UpdateConfig(request)
        # except Exception as e:
        #     print(f"ERROR: Failed to notify core engine: {e}")

notifier = WafNotifier()

def get_notifier():
    return notifier
